# Form implementation generated from reading ui file 'ui/CustomStatMaker.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class CustomStatMaker(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(377, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.MaxHP = QtWidgets.QSpinBox(parent=Dialog)
        self.MaxHP.setMaximum(9999999)
        self.MaxHP.setProperty("value", 120)
        self.MaxHP.setObjectName("MaxHP")
        self.horizontalLayout.addWidget(self.MaxHP)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.MeleeATK = QtWidgets.QSpinBox(parent=Dialog)
        self.MeleeATK.setMaximum(9999999)
        self.MeleeATK.setProperty("value", 100)
        self.MeleeATK.setObjectName("MeleeATK")
        self.horizontalLayout_2.addWidget(self.MeleeATK)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.MeleeDEF = QtWidgets.QSpinBox(parent=Dialog)
        self.MeleeDEF.setMaximum(100)
        self.MeleeDEF.setProperty("value", 100)
        self.MeleeDEF.setObjectName("MeleeDEF")
        self.horizontalLayout_3.addWidget(self.MeleeDEF)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.RangedATK = QtWidgets.QSpinBox(parent=Dialog)
        self.RangedATK.setMaximum(9999999)
        self.RangedATK.setProperty("value", 100)
        self.RangedATK.setObjectName("RangedATK")
        self.horizontalLayout_6.addWidget(self.RangedATK)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.RangedDEF = QtWidgets.QSpinBox(parent=Dialog)
        self.RangedDEF.setMaximum(9999999)
        self.RangedDEF.setProperty("value", 100)
        self.RangedDEF.setObjectName("RangedDEF")
        self.horizontalLayout_4.addWidget(self.RangedDEF)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Max HP"))
        self.label_3.setText(_translate("Dialog", "Melee Attack"))
        self.label.setText(_translate("Dialog", "Melee Defense"))
        self.label_6.setText(_translate("Dialog", "Ranged Attack"))
        self.label_4.setText(_translate("Dialog", "Ranged Defense"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = CustomStatMaker()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
