# Form implementation generated from reading ui file 'ui/mainMenu.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainMenu(object):
    def setupUi(self, MainMenu):
        MainMenu.setObjectName("MainMenu")
        MainMenu.resize(482, 299)
        self.centralwidget = QtWidgets.QWidget(parent=MainMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.dCalcButton = QtWidgets.QCommandLinkButton(parent=self.centralwidget)
        self.dCalcButton.setObjectName("dCalcButton")
        self.verticalLayout.addWidget(self.dCalcButton)
        self.sLoadoutButton = QtWidgets.QCommandLinkButton(parent=self.centralwidget)
        self.sLoadoutButton.setObjectName("sLoadoutButton")
        self.verticalLayout.addWidget(self.sLoadoutButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        MainMenu.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainMenu)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 482, 26))
        self.menubar.setObjectName("menubar")
        self.menuTools = QtWidgets.QMenu(parent=self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainMenu.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainMenu)
        self.statusbar.setObjectName("statusbar")
        MainMenu.setStatusBar(self.statusbar)
        self.actionCreate_Reset_Local_Database = QtGui.QAction(parent=MainMenu)
        self.actionCreate_Reset_Local_Database.setObjectName("actionCreate_Reset_Local_Database")
        self.actionCreate_Database_Tables = QtGui.QAction(parent=MainMenu)
        self.actionCreate_Database_Tables.setObjectName("actionCreate_Database_Tables")
        self.actionAdd_Monster_Data = QtGui.QAction(parent=MainMenu)
        self.actionAdd_Monster_Data.setObjectName("actionAdd_Monster_Data")
        self.actionAdd_Sticker_Data = QtGui.QAction(parent=MainMenu)
        self.actionAdd_Sticker_Data.setObjectName("actionAdd_Sticker_Data")
        self.menuTools.addAction(self.actionCreate_Reset_Local_Database)
        self.menuTools.addAction(self.actionCreate_Database_Tables)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionAdd_Monster_Data)
        self.menuTools.addAction(self.actionAdd_Sticker_Data)
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainMenu)
        QtCore.QMetaObject.connectSlotsByName(MainMenu)

    def retranslateUi(self, MainMenu):
        _translate = QtCore.QCoreApplication.translate
        MainMenu.setWindowTitle(_translate("MainMenu", "Heckahedron\'s Calcubelator"))
        self.dCalcButton.setText(_translate("MainMenu", "Damage Calculator"))
        self.dCalcButton.setDescription(_translate("MainMenu", "Calculate the damage done by one Monster to another.\n"
"Does not support Fusions right now."))
        self.sLoadoutButton.setText(_translate("MainMenu", "Party Editor"))
        self.sLoadoutButton.setDescription(_translate("MainMenu", "Select Monsters and equip stickers on them, without the hassle of the 2000 uncommons cluttering the menu."))
        self.menuTools.setTitle(_translate("MainMenu", "Tools"))
        self.actionCreate_Reset_Local_Database.setText(_translate("MainMenu", "Reset Database"))
        self.actionCreate_Database_Tables.setText(_translate("MainMenu", "Create Database Tables"))
        self.actionAdd_Monster_Data.setText(_translate("MainMenu", "Add Monster Data"))
        self.actionAdd_Sticker_Data.setText(_translate("MainMenu", "Add Sticker Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainMenu = QtWidgets.QMainWindow()
    ui = Ui_MainMenu()
    ui.setupUi(MainMenu)
    MainMenu.show()
    sys.exit(app.exec())
